import { useAuth } from "./context/AuthContext.jsx";
import { Link } from "react-router-dom";

const quickLinks = [
  { label: 'Authenticate users', description: 'Login, register, and manage profiles securely.', href: '#auth' },
  { label: 'Process payments', description: 'Authorize, capture, and refund transactions.', href: '#payments' },
  { label: 'Monitor fraud', description: 'Review alerts generated by the rule engine.', href: '#fraud' },
  { label: 'Admin controls', description: 'Configure roles and review audit logs.', href: '#admin' },
]

function App() {
  const { user, isAuthenticated, logout } = useAuth();

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100">
      <header className="border-b border-slate-800 bg-slate-900/60 backdrop-blur">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-3">
            <span className="flex h-10 w-10 items-center justify-center rounded-full bg-indigo-500 text-lg font-semibold text-white shadow shadow-indigo-500/60">
              PS
            </span>
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.35em] text-indigo-300">PaySecure Gateway</p>
              <p className="text-sm text-slate-300">Real-time payments control center</p>
            </div>
          </div>
          <div className="flex items-center gap-6">
            <nav className="hidden gap-6 text-sm font-medium text-slate-300 md:flex">
              <a className="transition hover:text-white" href="#auth">
                Auth
              </a>
              <a className="transition hover:text-white" href="#payments">
                Payments
              </a>
              <a className="transition hover:text-white" href="#fraud">
                Fraud
              </a>
              <a className="transition hover:text-white" href="#admin">
                Admin
              </a>
              <Link className="transition hover:text-white" to="/dashboard">
                Dashboard
              </Link>
            </nav>

            {isAuthenticated ? (
              <div className="flex items-center gap-3">
                <div className="text-right text-xs leading-tight text-slate-300">
                  <p className="font-semibold text-white">{user.firstName} {user.lastName}</p>
                  <p className="uppercase tracking-[0.35em] text-indigo-300">{user.role}</p>
                </div>
                <button
                  type="button"
                  onClick={logout}
                  className="rounded-full border border-slate-700 px-4 py-2 text-xs font-semibold text-slate-200 transition hover:border-rose-400 hover:text-rose-300"
                >
                  Log out
                </button>
              </div>
            ) : (
              <Link
                to="/auth/login"
                className="rounded-full border border-indigo-500 px-4 py-2 text-xs font-semibold text-indigo-200 transition hover:bg-indigo-500/10"
              >
                Log in
              </Link>
            )}
          </div>
        </div>
      </header>

      <main className="mx-auto flex max-w-5xl flex-col gap-12 px-6 py-16">
        <section className="rounded-3xl border border-slate-800 bg-slate-900/60 p-10 shadow-lg shadow-slate-900/70">
          <div className="flex flex-wrap items-start justify-between gap-8">
            <div className="max-w-xl space-y-4">
              <p className="text-sm font-semibold uppercase tracking-[0.3em] text-indigo-300">
                Welcome back
              </p>
              <h1 className="text-4xl font-semibold tracking-tight text-white sm:text-5xl">
                Manage the lifecycle of every PaySecure transaction
              </h1>
              <p className="text-lg leading-relaxed text-slate-300">
                This dashboard will become the control room for your payment gateway. We&apos;ll
                connect authentication, payment flows, fraud scoring, and admin tooling one step at a time.
              </p>
            </div>
            <div className="flex flex-col gap-3 rounded-2xl border border-slate-800 bg-slate-950/80 p-6 text-slate-200">
              <span className="text-xs font-semibold uppercase tracking-[0.4em] text-indigo-300">
                Next lesson
              </span>
              <p className="text-base font-medium">
                Build the authentication screen and wire it to the backend routes.
              </p>
              <a
                href="#learn-more"
                className="inline-flex items-center gap-2 text-sm font-semibold text-indigo-300 transition hover:text-indigo-200"
              >
                View learning plan
                <span aria-hidden>→</span>
              </a>
            </div>
          </div>
          <div className="mt-10 flex flex-wrap gap-4">
            <a
              href="http://localhost:3000/api-docs"
              className="inline-flex items-center justify-center rounded-full bg-indigo-500 px-6 py-3 text-sm font-semibold text-white shadow shadow-indigo-500/40 transition hover:bg-indigo-400"
            >
              Review API documentation
            </a>
            <a
              href="https://tailwindcss.com/docs"
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center justify-center rounded-full bg-slate-800 px-6 py-3 text-sm font-semibold text-slate-200 transition hover:bg-slate-700"
            >
              Tailwind reference
            </a>
          </div>
        </section>

        <section className="grid gap-6 md:grid-cols-2">
          {quickLinks.map((link) => (
            <article
              key={link.label}
              id={link.href.substring(1)}
              className="group h-full rounded-2xl border border-slate-800 bg-slate-900/60 p-6 shadow shadow-slate-950/40 transition hover:border-indigo-500/60 hover:shadow-indigo-500/20"
            >
              <p className="text-xs font-semibold uppercase tracking-[0.25em] text-indigo-300">
                {link.label}
              </p>
              <p className="mt-3 text-base text-slate-300">{link.description}</p>
              <span className="mt-6 inline-flex items-center text-sm font-semibold text-indigo-300 opacity-0 transition group-hover:opacity-100">
                Continue →
              </span>
            </article>
          ))}
        </section>
      </main>

      <footer className="border-t border-slate-800 bg-slate-900/60">
        <div className="mx-auto flex max-w-5xl flex-col gap-2 px-6 py-6 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between">
          <p>© {new Date().getFullYear()} PaySecure Gateway. Educational demo.</p>
          <p id="learn-more" className="text-slate-500">
            Tailwind utilities power every layout element on this page.
          </p>
        </div>
      </footer>
    </div>
  )
}

export default App
